### ISSUE TITLE
Typo in importdbfixture(s)

### ISSUE THREAD

**Issue by nhovratov** [peter-neumann-dev/ddev-cms-upgrader#3]
This should be aligned, so the script and command name are the same

https://github.com/peter-neumann-dev/ddev-cms-upgrader/blob/01d1e72959c67503f7a6d6f653115c6e30c57e6a/.ddev/commands/web/importdbfixture#L6

**Comment by peter-neumann-dev** [comment]
Thanks for mentioning 👍🏻
