### ISSUE TITLE
Wrong default path for db fixtures folder

### ISSUE THREAD

**Issue by nhovratov** [peter-neumann-dev/ddev-cms-upgrader#4]
The working directory is /var/www/html when I run a command. So `../fixtures/database/` does not work for me.

https://github.com/peter-neumann-dev/ddev-cms-upgrader/blob/01d1e72959c67503f7a6d6f653115c6e30c57e6a/.ddev/commands/web/importdbfixture#L12

**Comment by peter-neumann-dev** [comment]
Yep, that's right, according to the README, this folder is men to be in the project root. I will adjust it 🙂
